### ISSUE TITLE
Cannot define a function at init time when using global SV

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#352]
Tested with perl522 and B::C HEAD@67085929a153cf

Cannot define a function at init time when using an outer lexical SV

```perl
package Foo;

my $rand = 0;

INIT {
    *reader = sub () { $rand };
}

print qq/ok\n/;

1;
```

this test is flapping when trying to compile it
```
> for i in $(seq 1 5); do rm -f test.c test; perlcc -S -r test.pl || break; done
ok
sh: line 1:   600 Segmentation fault      /usr/local/cpanel/3rdparty/perl/522/bin/perl -I/root/.dotfiles/perl-must-have/lib -I/root/perl5/lib/perl5/ -I/usr/local/cpanel -MO=C,-otest.c test.pl 2> pccoNep8
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
collect2: ld returned 1 exit status
Can't exec "./test": No such file or directory at /usr/local/cpanel/3rdparty/perl/522/bin/perlcc line 136.
```

This is a regression coming from 7b1260f8efecdad99a43974ccc2f93b142085a81
for case #246 

Suggested patch
```diff
diff --git a/lib/B/C/OverLoad/B/CV.pm b/lib/B/C/OverLoad/B/CV.pm
index a303b33..30f3fe1 100644
--- a/lib/B/C/OverLoad/B/CV.pm
+++ b/lib/B/C/OverLoad/B/CV.pm
@@ -194,8 +194,9 @@ sub save {
     }

     if (
-        $isconst
+            $isconst
         and !is_phase_name($cvname)
+        and !( $CvFLAGS & CVf_ANON )

         # TODO: check if patch from e11e3a2 for B::SPECIAL is still required
         #    and ref($gv) ne 'B::SPECIAL'
```

**Comment by atoomic** [comment]
Note that this seems to only be an issue on CentOS 6 32 servers

**Comment by rurban** [comment]
This fix is already in B-C-1.53_01 as of your PR #353
