### ISSUE TITLE
perl-5.16.1 with ITHREADS: wrong CopSTASHPV_set

### ISSUE THREAD

**Issue by rurban** [rurban/perl-compiler#108]
Original [issue 106](https://code.google.com/p/perl-compiler/issues/detail?id=106) created by shlomif on 2012-08-26T09:54:22.000Z:

Hi,

when I build B-C-1.42 on perl-5.16.0 with ITHREADS enabled, I am getting these compilation errors:
```
shlomif[rpms]:$mageia/perl-B-C/SOURCES/B-C-1.42$ perl Makefile.PL 
Checking if your kit is complete...
Looks good
Writing Makefile for ByteLoader
Writing MYMETA.yml and MYMETA.json
Writing Makefile for B::Stash
Writing MYMETA.yml and MYMETA.json
Writing Makefile for B::C
Writing MYMETA.yml and MYMETA.json
shlomif[rpms]:$mageia/perl-B-C/SOURCES/B-C-1.42$ make test
make[1]: Entering directory `/home/shlomif/Download/unpack/Mageia/perl-B-C/SOURCES/B-C-1.42/ByteLoader'
cp BcVersions.pod ../blib/lib/BcVersions.pod
cp ByteLoader.pm ../blib/lib/ByteLoader.pm
cd .. &amp;&amp; /usr/bin/perl5.16.1 bytecode.pl &amp;&amp; cd ByteLoader
gcc -c   -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fPIC -Wl,--as-needed -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -pthread   -DVERSION=\&quot;0.09\&quot; -DXS_VERSION=\&quot;0.09\&quot; -fPIC &quot;-I/usr/lib/perl5/5.16.1/x86_64-linux-thread-multi/CORE&quot;   byterun.c
byterun.c: In function ‘byterun’:
byterun.c:1326:29: error: macro &quot;CopSTASHPV_set&quot; requires 3 arguments, but only 2 given
byterun.c:1326:3: error: ‘CopSTASHPV_set’ undeclared (first use in this function)
byterun.c:1326:3: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [byterun.o] Error 1
make[1]: Leaving directory `/home/shlomif/Download/unpack/Mageia/perl-B-C/SOURCES/B-C-1.42/ByteLoader'
make: *** [subdirs-test] Error 2
shlomif[rpms]:$mageia/perl-B-C/SOURCES/B-C-1.42$ 
```
This prevents me from updating it for Mageia 3/Cauldron. I'm on Mageia 3 on x86-64.

Regards,

-- Shlomi Fish

**Comment by toddr** [comment]
@shlomif, while getting 5.22 working, we've discovered some issues with 5.16. Are you ok with this working on 5.22 but not 5.16?

Also, at the moment, 5.16 will pass your reported problem against master.

**Comment by shlomif** [comment]
@toddr: I'm no longer actively using perl-5.16.x because Mageia 3 and Mageia 4 were end-of-lifed and Mageia 5 has perl-5.20.1 while Mageia Cauldron (which will become Mageia 6) has perl-5.22.x, so I'm personally fine with dropping support for perl-5.16.x.

**Comment by rurban** [comment]
Fixed some time ago. Tested fine with 5.16.3 threaded.
